export const EnglishDict = {
    main: 'Main',
    items: 'Items',
    champions: 'Champions',
    slogan: 'Analyze. Study. Win.',
    mainChampPromo: 'Learn the strengths and weaknesses of champions',
    role: 'Role',
    difficulty: 'Difficulty',
    abilities: 'Abilities',
    symbolInfo: '"?" indicates data not available from Riot API. You can confirm undisclosed values in League of Legends game client',
    cost: 'Cost(mana/energy):',
    cooldown: 'Cooldown(second):',
    goldCost: 'Price:',
    search: 'Search',
    level: 'Level',
    hours: 'hours',
    minutes: 'min',
    days: 'days',
    oneDay: 'Day',
    day: 'day',
    ago: 'ago',
    victory: 'Victory',
    defeat: 'Defeat',
    startItems: 'Starter Items',
    boots: 'Boots',
    epicItems: 'Epic Items',
    baseItems: 'Basic Items',
    legendaryItems: 'Legendary Items',
    ornnItems: 'Orrn Items'

}