export const EnglishDict = {
  main: 'Main',
  items: 'Items',
  champions: 'Champions',
  slogan: 'Analyze. Study. Win.',
  mainChampPromo: 'Learn the strengths and weaknesses of champions',
  role: 'Role',
  difficulty: 'Difficulty',
  abilities: 'Abilities',
  symbolInfo: '"?" indicates data not available from Riot API. You can confirm undisclosed values in League of Legends game client',
  cost: 'Cost(mana/energy):',
  cooldown: 'Cooldown(second):',
  goldCost: 'Price:',
  gold: 'gold',
  search: 'Search',
  level: 'Level',
  hours: 'hours',
  minutes: 'min',
  days: 'days',
  oneDay: 'Day',
  day: 'day',
  ago: 'ago',
  victory: 'Victory',
  defeat: 'Defeat',
  lowDifficulty: "Low",
  mediumDifficulty: "Medium",
  highDifficulty: "High",
  startItems: 'Starter Items',
  boots: 'Boots',
  epicItems: 'Epic Items',
  baseItems: 'Basic Items',
  legendaryItems: 'Legendary Items',
  ornnItems: 'Orrn Items',
  nothingFound: 'Nothing was found',
  baron: 'Baron',
  dragon: 'Dragon',
  horde: 'Voidgrub',
  inhibitor: 'Inhibitor',
  riftHerald: 'Rift Herald',
  tower: 'Tower',
  recentGames: 'Recent games',
  goldAdvantage: 'Team Gold Advantage',
  championKill: 'Champion Kill',
  goldEarned: 'Gold Earned',
  wardsPlaced: 'Wards Placed',
  creepStat: 'CS',
  CHALLENGER: 'Challenger',
  wins: 'Wins',
  losses: 'Defeats',
  damageDealt: 'Damage dealt',
  searchTooltip: 'Champion name or nickname(nickname#tag)',
  serverTooltip: 'Server selection',
  languageTooltip: 'Language',
  bestPlayers: 'Best players',
  mainPage: 'Go to Main page',
  pageNotFound: 'Page not found',
  pageNotFoundMessage: 'It seems something went wrong! The page you are requesting does not exist. It may be out of date, deleted, or an incorrect address was entered in the address bar.',
  accountErrorName: 'Player not found',
  accountError: "Unfortunately, the player was not found. Please check that you have selected the correct server and enter the player's nickname in the correct format: nickname#tag."

}