export const RussianDict = {
  champions: 'Чемпионы',
  main: 'Главная',
  items: 'Предметы',
  runes: 'Руны',
  slogan: 'Анализируй. Изучай. Побеждай.',
  mainChampPromo: 'Изучай сильные и слабые стороны чемпионов',
  role: 'Роль',
  difficulty: 'Сложность',
  abilities: 'Умения',
  symbolInfo: '"?" обозначает что данные не доступны с Riot API. Вы можете уточнить скрытые данные в клиенте игры League of Legends',
  cost: 'Стоимость(маны/энергии):',
  cooldown: 'Перезарядка(секунды):',
  goldCost: 'Стоимость:',
  gold: 'золота',
  search: 'Поиск',
  level: 'Уровень',
  hours: 'часов',
  minutes: 'мин',
  days: 'дней',
  oneDay: 'День',
  day: 'дня',
  ago: 'назад',
  victory: 'Победа',
  lowDifficulty: "Низкая",
  mediumDifficulty: "Средняя",
  highDifficulty: "Высокая",
  defeat: 'Поражение',
  startItems: 'Начальные предметы',
  boots: 'Ботинки',
  epicItems: 'Эпические предметы',
  baseItems: 'Базовые предметы',
  legendaryItems: 'Легендарные предметы',
  ornnItems: 'Предметы от Орна',
  nothingFound: 'Ничего не найдено',
  baron: 'Барон',
  dragon: 'Дракон',
  horde: 'Личинка бездны',
  inhibitor: 'Ингибитор',
  riftHerald: 'Герольд Бездны',
  tower: 'Башня',
  recentGames: 'Недавние игры',
  goldAdvantage: 'Командное преимущество в золоте',
  championKill: 'Чемпионов убито',
  goldEarned: 'Получено золота',
  wardsPlaced: 'Установлено тотемов',
  creepStat: 'Добивания',
  CHALLENGER: 'Претендент',
  wins: 'Побед',
  losses: 'Поражений',
  damageDealt: 'Нанесённый урон',
  searchTooltip: 'Имя чемпиона или никнейм(ник#тег)',
  serverTooltip: 'Выбор сервера',
  languageTooltip: 'Язык',
  bestPlayers: 'Лучшие игроки',
  mainPage: 'Перейти на главную',
  pageNotFound: 'Страница не найдена',
  pageNotFoundMessage: 'Кажется что-то пошло не так! Страница, которую вы запрашиваете, не существует. Возможно она устарела, была удалена, или введен неверный адрес в адресной строке.',
  accountErrorName: 'Игрок не найден',
  accountError: 'К сожалению, игрок не обнаружен. Пожалуйста, проверьте, что вы выбрали правильный сервер, и вводите ник игрока в правильном формате: ник#тег.'
}
