export const RussianDict = {
    champions: 'Чемпионы',
    main: 'Главная',
    items: 'Предметы',
    slogan: 'Анализируй. Изучай. Побеждай.',
    mainChampPromo: 'Изучай сильные и слабые стороны чемпионов',
    role: 'Роль',
    difficulty: 'Сложность',
    abilities: 'Умения',
    symbolInfo: '"?" обозначает что данные не доступны с Riot API. Вы можете уточнить скрытые данные в клиенте игры League of Legends',
    cost: 'Стоимость(маны/энергии):',
    cooldown: 'Перезарядка(секунды):',
    goldCost: 'Стоимость:',
    search: 'Поиск',
    level: 'Уровень',
    hours: 'часов',
    minutes: 'мин',
    days: 'дней',
    oneDay: 'День',
    day: 'дня',
    ago: 'назад',
    victory: 'Победа',
    defeat: 'Поражение',
    startItems: 'Начальные предметы',
    boots: 'Ботинки',
    epicItems: 'Эпические предметы',
    baseItems: 'Базовые предметы',
    legendaryItems: 'Легендарные предметы',
    ornnItems: 'Предметы от Орна'
}
